# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c1b91d669a27dfc9052816cfecdabd59b430cc0af106d3d4194b65e489ac9d7efbdc121e2411e6f6b94a1ca899405c6badfeeee67fb40ce725c86dba382ec0da

test:
  secret_key_base: 988a20df495c33de19810fe4f27732caadb1667ebf7557690013289251d736d944842a7ef69edf8998884321c4c584bf797e66a3e6bd197fbe585896e201beef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
